- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-all
      - puppet-openstack-beaker-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-cinder-tripleo-standalone
    gate:
      jobs:
        - puppet-cinder-tripleo-standalone

- job:
    name: puppet-cinder-tripleo-standalone
    parent: tripleo-puppet-ci-centos-7-standalone
    description: |
      TripleO standalone Job running Cinder specific Tempest tests.
    vars:
      featureset_override:
        run_tempest: true
        tempest_whitelist:
          - 'tempest.api.volume'
          - 'tempest.scenario.test_volume_boot_pattern'
          - 'cinder_tempest_plugin.api'
        tempest_plugins:
          - 'python-cinder-tests-tempest'
